# Generated by Django 4.2.3 on 2025-11-12 16:04

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('service', models.CharField(choices=[('NeoLite-Logistics', 'NeoLite Logistics'), ('Comone Express', 'Comone Express'), ('Direct Freight Express', 'Direct Freight Express'), ('Dex-i Express', 'Dex-i Express'), ('UPS Express', 'UPS Express'), ('ZeptoExpress', 'ZeptoExpress'), ('Pgeon Delivery', 'Pgeon Delivery'), ('Roadbull', 'Roadbull'), ('LWE', 'LWE'), ('SPC', 'SPC'), ('DHL Ecommerce', 'DHL Ecommerce')], max_length=50)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('in_transit', 'In Transit'), ('arrived_at_hub', 'Arrived at Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('delayed', 'Delayed'), ('on_hold', 'On Hold'), ('returned', 'Returned to Sender')], default='processing', max_length=30)),
                ('sender_name', models.CharField(max_length=255)),
                ('sender_contact', models.CharField(blank=True, max_length=100)),
                ('sender_address', models.TextField(blank=True)),
                ('receiver_name', models.CharField(max_length=255)),
                ('receiver_contact', models.CharField(blank=True, max_length=100)),
                ('receiver_address', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remarks', models.TextField(blank=True, help_text='Special instructions or notes', null=True)),
                ('current_location', models.CharField(blank=True, max_length=255)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_arrival', models.DateTimeField(blank=True, null=True)),
                ('map_location', models.TextField(blank=True, help_text='Paste Google Maps iframe URL here', null=True)),
                ('package_image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, verbose_name='Package Image')),
                ('id_document', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/demo/image/upload/sample.jpg', max_length=255, verbose_name='Receiver ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
    ]
